INSERT_INTO_POKEMON_INFO = """INSERT INTO ingredients_info VALUES(%s)"""

INSERT_INTO_DAIRY_INGREDIENTS = """INSERT INTO dairy_ingredients VALUES(%s)"""

INSERT_INTO_GLUTEN_INGREDIENTS = """INSERT INTO gluten_ingredients VALUES(%s)"""

